"""add updated/created to observations

Revision ID: 3967a578f902
Revises: ca6dba1b845b
Create Date: 2025-11-27 10:07:42.772518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3967a578f902'
down_revision: Union[str, Sequence[str], None] = 'ca6dba1b845b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_observations', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('weather_observations', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_observations', 'updated_at')
    op.drop_column('weather_observations', 'created_at')
    # ### end Alembic commands ###
