"""change raw response data to error data, use path for raw data, add finished at time to record latency

Revision ID: 4bcfdcf6e86a
Revises: a1cbf11c1945
Create Date: 2025-12-07 12:31:31.967193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4bcfdcf6e86a"
down_revision: Union[str, Sequence[str], None] = "a1cbf11c1945"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fetch_metadata",
        sa.Column("error_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "fetch_metadata", sa.Column("payload_path", sa.String(), nullable=True)
    )
    op.add_column(
        "fetch_metadata",
        sa.Column("finished_at", postgresql.TIMESTAMP(), nullable=True),
    )
    op.alter_column(
        "fetch_metadata",
        "request_url",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_column("fetch_metadata", "response_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fetch_metadata",
        sa.Column(
            "response_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "fetch_metadata",
        "request_url",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("fetch_metadata", "finished_at")
    op.drop_column("fetch_metadata", "payload_path")
    op.drop_column("fetch_metadata", "error_data")
    # ### end Alembic commands ###
