"""change fetch status to enum

Revision ID: a1cbf11c1945
Revises: 3967a578f902
Create Date: 2025-12-07 10:04:13.893855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1cbf11c1945"
down_revision: Union[str, Sequence[str], None] = "3967a578f902"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = postgresql.ENUM("PENDING", "ERROR", "SUCCESS", name="fetch_status")


def upgrade() -> None:
    """Upgrade schema."""

    op.alter_column("fetch_metadata", "status", server_default=None)
    op.execute("UPDATE fetch_metadata SET status = 'success' WHERE status = 'finished'")
    op.execute("UPDATE fetch_metadata SET status = UPPER(status)")

    status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fetch_metadata",
        "status",
        existing_type=sa.TEXT(),
        type_=status_enum,
        postgresql_using="status::fetch_status",
    )
    # ### end Alembic commands ###

    op.alter_column(
        "fetch_metadata",
        "status",
        server_default="PENDING",
    )


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fetch_metadata",
        "status",
        existing_type=status_enum,
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'::text"),
    )
    # ### end Alembic commands ###
    op.execute("UPDATE fetch_metadata SET status = UPPER(status)")
    op.execute("UPDATE fetch_metadata SET status = 'finished' WHERE status = 'success'")
    status_enum.drop(op.get_bind())
